name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master
    paths:
    - 'Jul2020/**'

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    
    env:
      BOOK_PATH: Jul2020
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r ${BOOK_PATH}/requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build ${BOOK_PATH}/

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./${BOOK_PATH}/_build/html

